'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("game2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _120px_Dark_Artistry_Tornado_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("120px-Dark_Artistry_Tornado_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _181717_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("181717-full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2603988_razor_eye_of_the_storm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2603988_razor_eye_of_the_storm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _286585_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("286585-small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44edf9dd3699febdc0c5183afcf5a025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("44edf9dd3699febdc0c5183afcf5a025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44edf9dd3699febdc0c5183afcf5a0251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("44edf9dd3699febdc0c5183afcf5a0251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5460c8f00ab38c43c030ebd59c3f546f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5460c8f00ab38c43c030ebd59c3f546f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adadadw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adadadw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adfafaf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adfafaf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arena_Battle_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arena_Battle_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asdasd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asdasd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Assassin_s_Creed_III_3_Connor_Kenway_DELUXE_PU_Axe_SAME_DAY_SHIPPING_Tomahawk_font_b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Assassin-s-Creed-III-3-Connor-Kenway-DELUXE-PU-Axe-SAME-DAY-SHIPPING-Tomahawk-fon"& _ 
                        "t-b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black_powerpoint_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black powerpoint background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bvnv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bvnv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dcn1adwq0ws() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dcn1adwq0ws", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dota_IMBA_LAGOONA_BLAZE_IT_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dota_IMBA_LAGOONA_BLAZE_IT_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eac5bd725ea8ac89a034fa6539d7e758() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eac5bd725ea8ac89a034fa6539d7e758", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eluci_Dator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eluci Dator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eluci_Dator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eluci Dator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property esports_dota_2_quai_rung_Satyr_Tormenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("esports_dota-2_quai-rung_Satyr-Tormenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excalibur_fantasy_weapons_4278339_800_600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excalibur-fantasy-weapons-4278339-800-600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jghjh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jghjh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjbjb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjbjb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kjhjk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjhjk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kopblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kopblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property merah_bintang_clip_art_vektor_gratis_download_241346() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("merah-bintang-clip-art-vektor-gratis-download-241346", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_icon_2970() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next-icon-2970", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Orang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Padded_Armor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Padded_Armor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pedang_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pedang 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property perisai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("perisai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Players() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Players", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sword_of_omens_by_ricardocoutinho_d496mgd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sword_of_omens_by_ricardocoutinho-d496mgd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sword1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sword1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wood_grain_texture_textured_wallpaper_dark_collection_images_textures_wallpapers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wood-grain-texture-textured-wallpaper-dark-collection-images-textures-wallpapers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property 멋진_사무라이_검_katana_열쇠_고리_keyring_pandent_japanes_애니메이션_만화_3_9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("멋진-사무라이-검-katana-열쇠-고리-keyring-pandent-japanes-애니메이션-만화-3-9-", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
